version: '3'

services:
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=production
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
  backend:
    build: ./backend
    command: ["python", "manage.py", "runserver"]
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"