version: '3'

services:
  frontend: 
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build: ./backend
    command: ["python", "manage.py", "runserver"]
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"